/**
 * WordPress dependencies
 */
import { __, sprintf } from '@wordpress/i18n';
import { cleanFieldName } from '../shared/utils';

const createInputField = ( fieldLabel, type, isRequired ) => {
	const labelBlock = { name: 'omniform/label' };
	const inputBlock = { name: 'omniform/input', attributes: { fieldType: type || 'text' } };

	const layout = [ 'checkbox', 'radio' ].includes( type )
		? { type: 'flex', orientation: 'horizontal', justifyContent: 'left' }
		: undefined;

	return ( {
		name: 'omniform/field',
		attributes: {
			fieldLabel,
			fieldName: cleanFieldName( fieldLabel ).toLowerCase(),
			isRequired,
			layout,
		},
		innerBlocks: [ 'checkbox', 'radio' ].includes( type )
			? [ inputBlock, labelBlock ]
			: [ labelBlock, inputBlock ],
	} );
};

const createSelectBlock = ( fieldLabel, options, isRequired ) => {
	const labelBlock = { name: 'omniform/label' };
	const inputBlock = { name: 'omniform/select', attributes: { fieldPlaceholder: __( 'Select One', 'omniform' ), isMultiple: false } };

	inputBlock.innerBlocks = options.map( ( option ) => ( {
		name: 'omniform/select-option',
		attributes: { fieldLabel: option },
	} ) );

	return ( {
		name: 'omniform/field',
		attributes: {
			fieldLabel,
			fieldName: cleanFieldName( fieldLabel ).toLowerCase(),
			isRequired,
		},
		innerBlocks: [ labelBlock, inputBlock ],
	} );
};

const variations = [
	{
		name: 'fieldset-radios',
		title: __( 'Multiple Choice', 'omniform' ),
		description: __( 'A fieldset containing multiple radio fields for exclusive choices.', 'omniform' ),
		attributes: {
			fieldLabel: __( 'Multiple Choice', 'omniform' ),
			fieldName: 'multiple-choice',
		},
		innerBlocks: [
			createInputField( __( 'Option One', 'omniform' ), 'radio' ),
			createInputField( __( 'Option Two', 'omniform' ), 'radio' ),
			createInputField( __( 'Option Three', 'omniform' ), 'radio' ),
		],
	},
	{
		name: 'fieldset-address-united-states',
		title: __( 'Address - United States', 'omniform' ),
		attributes: {
			fieldLabel: sprintf( '<strong>%s</strong>', __( 'Address', 'omniform' ) ),
			fieldName: 'address',
		},
		innerBlocks: [
			createInputField( __( 'Street Address', 'omniform' ), 'text', true ),
			createInputField( __( 'Address Line 2', 'omniform' ) ),
			{
				name: 'core/columns',
				attributes: {
					isStackedOnMobile: true,
				},
				innerBlocks: [
					{
						name: 'core/column',
						innerBlocks: [
							createInputField( __( 'City', 'omniform' ), 'text', true ),
						],
					},
					{
						name: 'core/column',
						innerBlocks: [
							createSelectBlock( __( 'State', 'omniform' ), [
								__( 'Alabama', 'omniform' ),
								__( 'Alaska', 'omniform' ),
								__( 'Arizona', 'omniform' ),
								__( 'Arkansas', 'omniform' ),
								__( 'California', 'omniform' ),
								__( 'Colorado', 'omniform' ),
								__( 'Connecticut', 'omniform' ),
								__( 'Delaware', 'omniform' ),
								__( 'District of Columbia', 'omniform' ),
								__( 'Florida', 'omniform' ),
								__( 'Georgia', 'omniform' ),
								__( 'Hawaii', 'omniform' ),
								__( 'Idaho', 'omniform' ),
								__( 'Illinois', 'omniform' ),
								__( 'Indiana', 'omniform' ),
								__( 'Iowa', 'omniform' ),
								__( 'Kansas', 'omniform' ),
								__( 'Kentucky', 'omniform' ),
								__( 'Louisiana', 'omniform' ),
								__( 'Maine', 'omniform' ),
								__( 'Maryland', 'omniform' ),
								__( 'Massachusetts', 'omniform' ),
								__( 'Michigan', 'omniform' ),
								__( 'Minnesota', 'omniform' ),
								__( 'Mississippi', 'omniform' ),
								__( 'Missouri', 'omniform' ),
								__( 'Montana', 'omniform' ),
								__( 'Nebraska', 'omniform' ),
								__( 'Nevada', 'omniform' ),
								__( 'New Hampshire', 'omniform' ),
								__( 'New Jersey', 'omniform' ),
								__( 'New Mexico', 'omniform' ),
								__( 'New York', 'omniform' ),
								__( 'North Carolina', 'omniform' ),
								__( 'North Dakota', 'omniform' ),
								__( 'Ohio', 'omniform' ),
								__( 'Oklahoma', 'omniform' ),
								__( 'Oregon', 'omniform' ),
								__( 'Pennsylvania', 'omniform' ),
								__( 'Rhode Island', 'omniform' ),
								__( 'South Carolina', 'omniform' ),
								__( 'South Dakota', 'omniform' ),
								__( 'Tennessee', 'omniform' ),
								__( 'Texas', 'omniform' ),
								__( 'Utah', 'omniform' ),
								__( 'Vermont', 'omniform' ),
								__( 'Virginia', 'omniform' ),
								__( 'Washington', 'omniform' ),
								__( 'West Virginia', 'omniform' ),
								__( 'Wisconsin', 'omniform' ),
								__( 'Wyoming', 'omniform' ),
							], true ),
						],
					},
				],
			},
			{
				name: 'core/columns',
				attributes: {
					isStackedOnMobile: true,
				},
				innerBlocks: [
					{
						name: 'core/column',
						innerBlocks: [
							createInputField( __( 'Zip Code', 'omniform' ), 'text', true ),
						],
					},
					{
						name: 'core/column',
					},
				],
			},
		],
	},
	{
		name: 'fieldset-address-canada',
		title: __( 'Address - Canada', 'omniform' ),
		attributes: {
			fieldLabel: sprintf( '<strong>%s</strong>', __( 'Address', 'omniform' ) ),
			fieldName: 'address',
		},
		innerBlocks: [
			createInputField( __( 'Street Address', 'omniform' ), 'text', true ),
			createInputField( __( 'Address Line 2', 'omniform' ) ),
			{
				name: 'core/columns',
				attributes: {
					isStackedOnMobile: true,
				},
				innerBlocks: [
					{
						name: 'core/column',
						attributes: {},
						innerBlocks: [
							createInputField( __( 'City', 'omniform' ), 'text', true ),
						],
					},
					{
						name: 'core/column',
						attributes: {},
						innerBlocks: [
							createSelectBlock( __( 'Province', 'omniform' ), [
								__( 'Alberta', 'omniform' ),
								__( 'British Columbia', 'omniform' ),
								__( 'Manitoba', 'omniform' ),
								__( 'New Brunswick', 'omniform' ),
								__( 'Newfoundland', 'omniform' ),
								__( 'Northwest Territories', 'omniform' ),
								__( 'Nova Scotia', 'omniform' ),
								__( 'Nunavut', 'omniform' ),
								__( 'Ontario', 'omniform' ),
								__( 'Prince Edward Island', 'omniform' ),
								__( 'Quebec', 'omniform' ),
								__( 'Saskatchewan', 'omniform' ),
								__( 'Yukon', 'omniform' ),
							], true ),
						],
					},
				],
			},
			{
				name: 'core/columns',
				attributes: {
					isStackedOnMobile: true,
				},
				innerBlocks: [
					{
						name: 'core/column',
						attributes: {},
						innerBlocks: [
							createInputField( __( 'Postal Code', 'omniform' ), 'text', true ),
						],
					},
					{
						name: 'core/column',
						attributes: {},
					},
				],
			},
		],
	},
	{
		name: 'fieldset-address-international',
		title: __( 'Address - International', 'omniform' ),
		attributes: {
			fieldLabel: sprintf( '<strong>%s</strong>', __( 'Address', 'omniform' ) ),
			fieldName: 'address',
		},
		innerBlocks: [
			createInputField( __( 'Street Address', 'omniform' ), 'text', true ),
			createInputField( __( 'Address Line 2', 'omniform' ) ),
			{
				name: 'core/columns',
				attributes: {
					isStackedOnMobile: true,
				},
				innerBlocks: [
					{
						name: 'core/column',
						attributes: {},
						innerBlocks: [
							createInputField( __( 'City', 'omniform' ), 'text', true ),
						],
					},
					{
						name: 'core/column',
						attributes: {},
						innerBlocks: [
							createInputField( __( 'State / Province / Region', 'omniform' ), 'text', true ),
						],
					},
				],
			},
			{
				name: 'core/columns',
				attributes: {
					isStackedOnMobile: true,
				},
				innerBlocks: [
					{
						name: 'core/column',
						attributes: {},
						innerBlocks: [
							createInputField( __( 'Zip / Postal Code', 'omniform' ), 'text', true ),
						],
					},
					{
						name: 'core/column',
						attributes: {},
						innerBlocks: [
							createSelectBlock( __( 'Country / Territory', 'omniform' ), [
								__( 'Afghanistan', 'omniform' ),
								__( 'Aland Islands', 'omniform' ),
								__( 'Albania', 'omniform' ),
								__( 'Algeria', 'omniform' ),
								__( 'American Samoa', 'omniform' ),
								__( 'Andorra', 'omniform' ),
								__( 'Angola', 'omniform' ),
								__( 'Anguilla', 'omniform' ),
								__( 'Antigua & Barbuda', 'omniform' ),
								__( 'Argentina', 'omniform' ),
								__( 'Armenia', 'omniform' ),
								__( 'Aruba', 'omniform' ),
								__( 'Australia', 'omniform' ),
								__( 'Austria', 'omniform' ),
								__( 'Azerbaijan', 'omniform' ),
								__( 'Azores', 'omniform' ),
								__( 'Bahamas', 'omniform' ),
								__( 'Bahrain', 'omniform' ),
								__( 'Bangladesh', 'omniform' ),
								__( 'Barbados', 'omniform' ),
								__( 'Belarus', 'omniform' ),
								__( 'Belgium', 'omniform' ),
								__( 'Belize', 'omniform' ),
								__( 'Benin', 'omniform' ),
								__( 'Bermuda', 'omniform' ),
								__( 'Bhutan', 'omniform' ),
								__( 'Bolivia', 'omniform' ),
								__( 'Bonaire', 'omniform' ),
								__( 'St. Eustatius', 'omniform' ),
								__( 'Saba', 'omniform' ),
								__( 'Bosnia', 'omniform' ),
								__( 'Botswana', 'omniform' ),
								__( 'Brazil', 'omniform' ),
								__( 'British Virgin Isles', 'omniform' ),
								__( 'Brunei', 'omniform' ),
								__( 'Bulgaria', 'omniform' ),
								__( 'Burkina Faso', 'omniform' ),
								__( 'Burundi', 'omniform' ),
								__( 'Cambodia', 'omniform' ),
								__( 'Cameroon', 'omniform' ),
								__( 'Canada', 'omniform' ),
								__( 'Canary Islands', 'omniform' ),
								__( 'Cape Verde', 'omniform' ),
								__( 'Cayman Islands', 'omniform' ),
								__( 'Central African Republic', 'omniform' ),
								__( 'Ceuta', 'omniform' ),
								__( 'Chad', 'omniform' ),
								__( 'Chile', 'omniform' ),
								__( 'China Mainland', 'omniform' ),
								__( 'Colombia', 'omniform' ),
								__( 'Comoros', 'omniform' ),
								__( 'Congo', 'omniform' ),
								__( 'Cook Islands', 'omniform' ),
								__( 'Costa Rica', 'omniform' ),
								__( 'Croatia', 'omniform' ),
								__( 'Curacao', 'omniform' ),
								__( 'Cyprus', 'omniform' ),
								__( 'Czech Republic', 'omniform' ),
								__( 'Democratic Republic of Congo', 'omniform' ),
								__( 'Cuba', 'omniform' ),
								__( 'Denmark', 'omniform' ),
								__( 'Djibouti', 'omniform' ),
								__( 'Dominica', 'omniform' ),
								__( 'Dominican Republic', 'omniform' ),
								__( 'Ecuador', 'omniform' ),
								__( 'Egypt', 'omniform' ),
								__( 'El Salvador', 'omniform' ),
								__( 'England', 'omniform' ),
								__( 'Equatorial Guinea', 'omniform' ),
								__( 'Eritrea', 'omniform' ),
								__( 'Estonia', 'omniform' ),
								__( 'Ethiopia', 'omniform' ),
								__( 'Faeroe Islands', 'omniform' ),
								__( 'Fiji', 'omniform' ),
								__( 'Finland', 'omniform' ),
								__( 'France', 'omniform' ),
								__( 'French Guiana', 'omniform' ),
								__( 'French Polynesia', 'omniform' ),
								__( 'Gabon', 'omniform' ),
								__( 'Gambia', 'omniform' ),
								__( 'Georgia', 'omniform' ),
								__( 'Germany', 'omniform' ),
								__( 'Ghana', 'omniform' ),
								__( 'Gibraltar', 'omniform' ),
								__( 'Greece', 'omniform' ),
								__( 'Greenland', 'omniform' ),
								__( 'Grenada', 'omniform' ),
								__( 'Guadeloupe', 'omniform' ),
								__( 'Guam', 'omniform' ),
								__( 'Guatemala', 'omniform' ),
								__( 'Guernsey', 'omniform' ),
								__( 'Guinea', 'omniform' ),
								__( 'Guinea-Bissau', 'omniform' ),
								__( 'Guyana', 'omniform' ),
								__( 'Haiti', 'omniform' ),
								__( 'Holland', 'omniform' ),
								__( 'Honduras', 'omniform' ),
								__( 'Hong Kong SAR', 'omniform' ),
								__( 'China', 'omniform' ),
								__( 'Hungary', 'omniform' ),
								__( 'Iceland', 'omniform' ),
								__( 'India', 'omniform' ),
								__( 'Indonesia', 'omniform' ),
								__( 'Iraq', 'omniform' ),
								__( 'Ireland', 'omniform' ),
								__( 'Republic of', 'omniform' ),
								__( 'Israel', 'omniform' ),
								__( 'Italy', 'omniform' ),
								__( 'Ivory Coast', 'omniform' ),
								__( 'Jamaica', 'omniform' ),
								__( 'Japan', 'omniform' ),
								__( 'Jersey', 'omniform' ),
								__( 'Jordan', 'omniform' ),
								__( 'Kazakhstan', 'omniform' ),
								__( 'Kenya', 'omniform' ),
								__( 'Kiribati', 'omniform' ),
								__( 'Kosovo', 'omniform' ),
								__( 'Kosrae', 'omniform' ),
								__( 'Kuwait', 'omniform' ),
								__( 'Kyrgyzstan', 'omniform' ),
								__( 'Laos', 'omniform' ),
								__( 'Latvia', 'omniform' ),
								__( 'Lebanon', 'omniform' ),
								__( 'Lesotho', 'omniform' ),
								__( 'Liberia', 'omniform' ),
								__( 'Libya', 'omniform' ),
								__( 'Liechtenstein', 'omniform' ),
								__( 'Lithuania', 'omniform' ),
								__( 'Luxembourg', 'omniform' ),
								__( 'Macau SAR', 'omniform' ),
								__( 'China', 'omniform' ),
								__( 'Macedonia (Fyrom)', 'omniform' ),
								__( 'Madagascar', 'omniform' ),
								__( 'Madeira', 'omniform' ),
								__( 'Malawi', 'omniform' ),
								__( 'Malaysia', 'omniform' ),
								__( 'Maldives', 'omniform' ),
								__( 'Mali', 'omniform' ),
								__( 'Malta', 'omniform' ),
								__( 'Marshall Islands', 'omniform' ),
								__( 'Martinique', 'omniform' ),
								__( 'Mauritania', 'omniform' ),
								__( 'Mauritius', 'omniform' ),
								__( 'Mayotte', 'omniform' ),
								__( 'Melilla', 'omniform' ),
								__( 'Mexico', 'omniform' ),
								__( 'Micronesia', 'omniform' ),
								__( 'Moldova', 'omniform' ),
								__( 'Monaco', 'omniform' ),
								__( 'Mongolia', 'omniform' ),
								__( 'Montenegro', 'omniform' ),
								__( 'Montserrat', 'omniform' ),
								__( 'Morocco', 'omniform' ),
								__( 'Mozambique', 'omniform' ),
								__( 'N. Mariana Islands', 'omniform' ),
								__( 'Namibia', 'omniform' ),
								__( 'Nepal', 'omniform' ),
								__( 'Netherlands', 'omniform' ),
								__( 'New Caledonia', 'omniform' ),
								__( 'New Zealand', 'omniform' ),
								__( 'Nicaragua', 'omniform' ),
								__( 'Niger', 'omniform' ),
								__( 'Nigeria', 'omniform' ),
								__( 'Norfolk Island', 'omniform' ),
								__( 'Northern Ireland', 'omniform' ),
								__( 'Norway', 'omniform' ),
								__( 'Oman', 'omniform' ),
								__( 'Pakistan', 'omniform' ),
								__( 'Palau', 'omniform' ),
								__( 'Panama', 'omniform' ),
								__( 'Papua New Guinea', 'omniform' ),
								__( 'Paraguay', 'omniform' ),
								__( 'Peru', 'omniform' ),
								__( 'Philippines', 'omniform' ),
								__( 'Poland', 'omniform' ),
								__( 'Ponape', 'omniform' ),
								__( 'Portugal', 'omniform' ),
								__( 'Puerto Rico', 'omniform' ),
								__( 'Qatar', 'omniform' ),
								__( 'Reunion', 'omniform' ),
								__( 'Romania', 'omniform' ),
								__( 'Rota', 'omniform' ),
								__( 'Rwanda', 'omniform' ),
								__( 'Saba', 'omniform' ),
								__( 'Saipan', 'omniform' ),
								__( 'Samoa', 'omniform' ),
								__( 'Sao Tome/Principe', 'omniform' ),
								__( 'San Marino', 'omniform' ),
								__( 'Saudi Arabia', 'omniform' ),
								__( 'Scotland', 'omniform' ),
								__( 'Senegal', 'omniform' ),
								__( 'Serbia', 'omniform' ),
								__( 'Seychelles', 'omniform' ),
								__( 'Sierra Leone', 'omniform' ),
								__( 'Singapore', 'omniform' ),
								__( 'Slovakia', 'omniform' ),
								__( 'Slovenia', 'omniform' ),
								__( 'Solomon Islands', 'omniform' ),
								__( 'South Africa', 'omniform' ),
								__( 'South Korea', 'omniform' ),
								__( 'Spain', 'omniform' ),
								__( 'Sri Lanka', 'omniform' ),
								__( 'St. Barthelemy', 'omniform' ),
								__( 'St. Christopher', 'omniform' ),
								__( 'St. Croix', 'omniform' ),
								__( 'St. Eustatius', 'omniform' ),
								__( 'St. John', 'omniform' ),
								__( 'St. Kitts & Nevis', 'omniform' ),
								__( 'St. Lucia', 'omniform' ),
								__( 'St. Maarten and St. Martin', 'omniform' ),
								__( 'St. Thomas', 'omniform' ),
								__( 'St. Vincent/Grenadines', 'omniform' ),
								__( 'Suriname', 'omniform' ),
								__( 'Swaziland', 'omniform' ),
								__( 'Sweden', 'omniform' ),
								__( 'Switzerland', 'omniform' ),
								__( 'Tahiti', 'omniform' ),
								__( 'Taiwan', 'omniform' ),
								__( 'China', 'omniform' ),
								__( 'Tajikistan', 'omniform' ),
								__( 'Tanzania', 'omniform' ),
								__( 'Thailand', 'omniform' ),
								__( 'Timor Leste', 'omniform' ),
								__( 'Tinian', 'omniform' ),
								__( 'Togo', 'omniform' ),
								__( 'Tonga', 'omniform' ),
								__( 'Tortola', 'omniform' ),
								__( 'Trinidad & Tobago', 'omniform' ),
								__( 'Truk', 'omniform' ),
								__( 'Tunisia', 'omniform' ),
								__( 'Turkey', 'omniform' ),
								__( 'Turkmenistan', 'omniform' ),
								__( 'Turks & Caicos Islands', 'omniform' ),
								__( 'Tuvalu', 'omniform' ),
								__( 'Uganda', 'omniform' ),
								__( 'Ukraine', 'omniform' ),
								__( 'Union Island', 'omniform' ),
								__( 'United Arab Emirates', 'omniform' ),
								__( 'United Kingdom', 'omniform' ),
								__( 'United States', 'omniform' ),
								__( 'Uruguay', 'omniform' ),
								__( 'US Virgin Islands', 'omniform' ),
								__( 'Uzbekistan', 'omniform' ),
								__( 'Vanuatu', 'omniform' ),
								__( 'Vatican City State', 'omniform' ),
								__( 'Venezuela', 'omniform' ),
								__( 'Vietnam', 'omniform' ),
								__( 'Virgin Gorda', 'omniform' ),
								__( 'Wales', 'omniform' ),
								__( 'Wallis & Futuna Islands', 'omniform' ),
								__( 'Yap', 'omniform' ),
								__( 'Yemen', 'omniform' ),
								__( 'Zambia', 'omniform' ),
								__( 'Zimbabwe', 'omniform' ),
							], true ),
						],
					},
				],
			},
		],
	},
];

export default variations;
