name: Build release zip

on:
  workflow_run:
    workflows: [Static Analysis]
    types: [completed]
  workflow_dispatch:

jobs:

  on-success:
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v3

      - name: Restore npm dependency cache
        uses: ./.github/actions/restore-npm-cache
      - run: npm install

      - name: Build scripts
        run: npm run build

      - name: Install PHP-Scoper
        run: composer global require humbug/php-scoper

      - name: Install WP CLI
        run: |
          composer global require wp-cli/wp-cli-bundle
          composer global require wp-cli/dist-archive-command

      - name: Add Composer bin to PATH
        run: echo "$HOME/.composer/vendor/bin/" >> $GITHUB_PATH

      - name: Install composer dependencies
        run: composer run phpscoper

      - name: Generate zip
        run: wp dist-archive ./ ${{ github.event.repository.name }}.zip

      - name: Unzip the archive (prevents double zip problem)
        run: unzip ${{ github.event.repository.name }}.zip -d zipfile
        shell: bash

      - name: Upload the archive as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}
          path: zipfile
          retention-days: 5

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
